name: Upload Python Package

on:
  release:
    types: [created]

jobs:
    publish-mac-windows:
        strategy:
          matrix:
            python-version: ["3.6.x", "3.7.x", "3.8.x", "3.9.x", "3.10.x", "3.11.x"]
            os: [macos-12, windows-2022]
        runs-on: ${{matrix.os}}
        steps:
        - name: setup macos
          if: matrix.os == 'macos-12'
          run: brew install tbb
        - uses: actions/checkout@v2
        - name: Set up Python
          uses: actions/setup-python@v2
          with:
            python-version: ${{matrix.python-version}}
            architecture: ${{matrix.architecture}}
        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip
            pip install setuptools wheel twine 
        - name: Build and publish
          env:
            TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
            TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
          run: |
            python setup.py bdist_wheel
            twine upload dist/*

    publish-unix:
        runs-on: ubuntu-20.04
        steps:
        - name: setup ubuntu
          if: matrix.os == 'ubuntu-20.04'
          run: |
            sudo apt update
            sudo apt install libtbb-dev
        - uses: actions/checkout@v2
          with:
            submodules: true
        - name: Set up Python
          uses: actions/setup-python@v2
          with:
            python-version: "3.x"
        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip
            pip install setuptools wheel twine 
        - name: build manylinux
          uses: RalfG/python-wheels-manylinux-build@v0.5.0-manylinux2014_x86_64
          with: 
            system-packages: 'ninja-build'
        - name: Publish manylinux
          env:
            TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
            TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
          run: |
            twine upload dist/*-manylinux*.whl
        - name: Build and publish source
          env:
            TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
            TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
          run: |
            python setup.py sdist
            twine upload dist/*.tar.gz     
