name: MacOS

on: [push]

jobs:
  build-test-python:
    runs-on: [macos-latest, ubuntu-20.04, windows-2022]
    strategy:
      matrix:
        python-version: ["3.6.x", "3.7.x", "3.8.x", "3.9.x", "3.10.x", "3.11.x"]
        compiler: [g++]
        architecture: [x64]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      env:
        CXX: ${{ matrix.compiler }}
      with:
        python-version: ${{matrix.python-version}}
        architecture: ${{matrix.architecture}}
    - name: Install library
      run: |
        python -m pip install --upgrade pip
        pip install -e . -v
    - name: Run unit tests
      run: python -m unittest -v
